# Day 22 part 1
# What is the sum of the 2000th secret number generated by each buyer?

filename = "test22.txt"
filename = "input22.txt"
MOD_NUM = 16_777_216
GEN_NUM = 2000

with open(filename) as f:
    ls = f.read().strip().split("\n")

seeds = [int(x) for x in ls]

def step1(n):
    m = n * 64
    # mix
    n = n ^ m
    # prune
    return(n % MOD_NUM)

def step2(n):
    m = n // 32
    n = n ^ m
    return(n % MOD_NUM)

def step3(n):
    m = n * 2048
    n = n ^ m
    return(n % MOD_NUM)

nth_list = []
for seed in seeds:
    num = seed
    for i in range(GEN_NUM):
        num = step3(step2(step1(num)))
    nth_list.append(num)
print(sum(nth_list))
